In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

In [2]:
veriler = pd.read_csv("veriler.csv")

In [3]:
veriler

   ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k

In [4]:
boy = veriler[["boy"]]

In [5]:
boy

    boy
0   130
1   125
2   135
3   133
4   129
5   180
6   190
7   175
8   177
9   185
10  165
11  155
12  160
13  162
14  167
15  174
16  193
17  187
18  183
19  159
20  164
21  166

In [6]:
boyKilo = veriler[["boy","kilo"]]

In [7]:
boyKilo

    boy  kilo
0   130    30
1   125    36
2   135    34
3   133    30
4   129    38
5   180    90
6   190    80
7   175    90
8   177    60
9   185   105
10  165    55
11  155    50
12  160    58
13  162    59
14  167    62
15  174    70
16  193    90
17  187    80
18  183    88
19  159    40
20  164    66
21  166    56

In [8]:
imputer = SimpleImputer(missing_values=np.nan,strategy="mean")
Yas = veriler.iloc[:,1:4].values
Yas

array([[130,  30,  10],
       [125,  36,  11],
       [135,  34,  10],
       [133,  30,   9],
       [129,  38,  12],
       [180,  90,  30],
       [190,  80,  25],
       [175,  90,  35],
       [177,  60,  22],
       [185, 105,  33],
       [165,  55,  27],
       [155,  50,  44],
       [160,  58,  39],
       [162,  59,  41],
       [167,  62,  55],
       [174,  70,  47],
       [193,  90,  23],
       [187,  80,  27],
       [183,  88,  28],
       [159,  40,  29],
       [164,  66,  32],
       [166,  56,  42]], dtype=int64)

In [9]:
imputer = imputer.fit(Yas[:,1:4])
Yas[:,1:4] = imputer.transform(Yas[:,1:4])
Yas
#Bu kısma kadar şayet varsa eksik veriler giderildi

array([[130,  30,  10],
       [125,  36,  11],
       [135,  34,  10],
       [133,  30,   9],
       [129,  38,  12],
       [180,  90,  30],
       [190,  80,  25],
       [175,  90,  35],
       [177,  60,  22],
       [185, 105,  33],
       [165,  55,  27],
       [155,  50,  44],
       [160,  58,  39],
       [162,  59,  41],
       [167,  62,  55],
       [174,  70,  47],
       [193,  90,  23],
       [187,  80,  27],
       [183,  88,  28],
       [159,  40,  29],
       [164,  66,  32],
       [166,  56,  42]], dtype=int64)

In [10]:
#Kategori -> Numeric
ulke = veriler.iloc[:,0:1].values
ulke

array([['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr']], dtype=object)

In [11]:
le = preprocessing.LabelEncoder()
ulke[:,0] = le.fit_transform(veriler.iloc[:,0])
ulke

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=object)

In [12]:
ohe = preprocessing.OneHotEncoder()
ulke = ohe.fit_transform(ulke).toarray()
ulke

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [13]:
#cinsiyet => numeric
cinsiyet = veriler.iloc[:,-1:].values
le = preprocessing.LabelEncoder()
cinsiyet[:,-1] = le.fit_transform(veriler.iloc[:,-1])
cinsiyet

array([[0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1]], dtype=object)

In [14]:
#Kolonları oluşturulması işlemi
sonuc = pd.DataFrame(data=ulke,index=range(22),columns=["fr","tr","us"])
sonuc2 = pd.DataFrame(data=Yas , index=range(22),columns=["boy","kilo","yas"])
sonuc3 = pd.DataFrame(data=cinsiyet[:,:1],index=range(22),columns=["cinsiyet"])

In [15]:
#Kolonların birleştirilmesi işlemi
s = pd.concat([sonuc,sonuc2],axis=1)

In [16]:
s2 = pd.concat([s,sonuc3],axis=1)
s2

     fr   tr   us  boy  kilo  yas cinsiyet
0   0.0  1.0  0.0  130    30   10        0
1   0.0  1.0  0.0  125    36   11        0
2   0.0  1.0  0.0  135    34   10        1
3   0.0  1.0  0.0  133    30    9        1
4   0.0  1.0  0.0  129    38   12        0
5   0.0  1.0  0.0  180    90   30        0
6   0.0  1.0  0.0  190    80   25        0
7   0.0  1.0  0.0  175    90   35        0
8   0.0  1.0  0.0  177    60   22        1
9   0.0  0.0  1.0  185   105   33        0
10  0.0  0.0  1.0  165    55   27        1
11  0.0  0.0  1.0  155    50   44        1
12  0.0  0.0  1.0  160    58   39        1
13  0.0  0.0  1.0  162    59   41        1
14  0.0  0.0  1.0  167    62   55        1
15  1.0  0.0  0.0  174    70   47        0
16  1.0  0.0  0.0  193    90   23        0
17  1.0  0.0  0.0  187    80   27        0
18  1.0  0.0  0.0  183    88   28        0
19  1.0  0.0  0.0  159    40   29        1
20  1.0  0.0  0.0  164    66   32        1
21  1.0  0.0  0.0  166    56   42        1

In [17]:
x_train , x_test , y_train , y_test = train_test_split(s,sonuc3 ,test_size=0.33,random_state=0)

In [18]:
y_train

   cinsiyet
8         1
6         0
16        0
4         0
2         1
5         0
17        0
9         0
7         0
18        0
3         1
0         0
15        0
12        1

In [19]:
regressor = LinearRegression()
regressor.fit(x_train,y_train) #Modelin Eğitim Aşaması
y_pred = regressor.predict(x_test)

In [20]:
y_pred

array([[0.01279796],
       [1.12036863],
       [0.94990297],
       [0.92862582],
       [0.27526065],
       [0.35384956],
       [1.03567453],
       [0.67387829]])

In [21]:
#Tüm verilere bakılarak boy verisini tahmin etme işlemi .
boy = s2.iloc[:,3:4].values
sol = s2.iloc[:,:3]
sag = s2.iloc[:,4:]
veri = pd.concat([sol,sag],axis=1)
yeni_x_train , yeni_x_test , yeni_y_train , yeni_y_test = train_test_split(veri,boy,test_size=0.33,random_state=0)
r2 = LinearRegression()
r2.fit(yeni_x_train,yeni_y_train)
yeni_y_pred = r2.predict(yeni_x_test)
yeni_y_pred

array([[182.26638686],
       [152.87161474],
       [162.79386375],
       [158.30668577],
       [130.82888952],
       [173.96138408],
       [150.12782663],
       [157.26898922]])

In [29]:
#Verilerin Sonuç üzerindeki etkileri belirleme işlemi
X = np.append(arr=np.ones((22,1)).astype(int),values=veri,axis=1)
X_L = veri.iloc[:,[0,1,2,3,4,5]].values
X_L = np.array(X_L,dtype = float)
model = sm.OLS(boy,X_L).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.885
Model:                            OLS   Adj. R-squared:                  0.849
Method:                 Least Squares   F-statistic:                     24.69
Date:                Sun, 25 Aug 2024   Prob (F-statistic):           5.41e-07
Time:                        09:22:18   Log-Likelihood:                -73.950
No. Observations:                  22   AIC:                             159.9
Df Residuals:                      16   BIC:                             166.4
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           103.4708      9.878     10.475      0.000      82.530     124.412
x2            97.7050      7.463     13.091      0.000      81.883     113.527
x3            93.8734     11.312      8.298      0.000      69.892     117.855
x4             0.9211      0.119      7.737      0.000       0.669       1.174
x5             0.0814      0.221      0.369      0.717      -0.386       0.549
x6            10.5980      5.052      2.098      0.052      -0.112      21.308
==============================================================================
Omnibus:                        1.031   Durbin-Watson:                   2.759
Prob(Omnibus):                  0.597   Jarque-Bera (JB):                0.624
Skew:                           0.407   Prob(JB):                        0.732
Kurtosis:                       2.863   Cond. No.                         678.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [30]:
#En Yüksek Değerdekini eleyerek tekrar bir model oluşturduk
#X = np.append(arr=np.ones((22,1)).astype(int),values=veri,axis=1)
X_L = veri.iloc[:,[0,1,2,3,5]].values
X_L = np.array(X_L,dtype = float)
model = sm.OLS(boy,X_L).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.884
Model:                            OLS   Adj. R-squared:                  0.857
Method:                 Least Squares   F-statistic:                     32.47
Date:                Sun, 25 Aug 2024   Prob (F-statistic):           9.32e-08
Time:                        09:22:45   Log-Likelihood:                -74.043
No. Observations:                  22   AIC:                             158.1
Df Residuals:                      17   BIC:                             163.5
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           104.5490      9.193     11.373      0.000      85.153     123.944
x2            97.9693      7.238     13.536      0.000      82.699     113.240
x3            95.4352     10.220      9.338      0.000      73.873     116.998
x4             0.9405      0.104      9.029      0.000       0.721       1.160
x5            11.1093      4.733      2.347      0.031       1.123      21.096
==============================================================================
Omnibus:                        0.871   Durbin-Watson:                   2.719
Prob(Omnibus):                  0.647   Jarque-Bera (JB):                0.459
Skew:                           0.351   Prob(JB):                        0.795
Kurtosis:                       2.910   Cond. No.                         596.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [31]:
#En Yüksek Değerdekini eleyerek tekrar bir model oluşturduk
#X = np.append(arr=np.ones((22,1)).astype(int),values=veri)
X_L = veri.iloc[:,[0,1,2,3]].values
X_L = np.array(X_L,dtype = float)
model = sm.OLS(boy,X_L).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.847
Model:                            OLS   Adj. R-squared:                  0.821
Method:                 Least Squares   F-statistic:                     33.16
Date:                Sun, 25 Aug 2024   Prob (F-statistic):           1.52e-07
Time:                        09:23:31   Log-Likelihood:                -77.131
No. Observations:                  22   AIC:                             162.3
Df Residuals:                      18   BIC:                             166.6
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           119.8136      7.265     16.491      0.000     104.550     135.077
x2           109.8084      5.804     18.919      0.000      97.615     122.002
x3           114.4212      6.984     16.382      0.000      99.747     129.095
x4             0.7904      0.092      8.595      0.000       0.597       0.984
==============================================================================
Omnibus:                        2.925   Durbin-Watson:                   2.855
Prob(Omnibus):                  0.232   Jarque-Bera (JB):                1.499
Skew:                           0.605   Prob(JB):                        0.473
Kurtosis:                       3.416   Cond. No.                         369.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

array([[1, 0.0, 1.0, 0.0, 30, 10, 0],
       [1, 0.0, 1.0, 0.0, 36, 11, 0],
       [1, 0.0, 1.0, 0.0, 34, 10, 1],
       [1, 0.0, 1.0, 0.0, 30, 9, 1],
       [1, 0.0, 1.0, 0.0, 38, 12, 0],
       [1, 0.0, 1.0, 0.0, 90, 30, 0],
       [1, 0.0, 1.0, 0.0, 80, 25, 0],
       [1, 0.0, 1.0, 0.0, 90, 35, 0],
       [1, 0.0, 1.0, 0.0, 60, 22, 1],
       [1, 0.0, 0.0, 1.0, 105, 33, 0],
       [1, 0.0, 0.0, 1.0, 55, 27, 1],
       [1, 0.0, 0.0, 1.0, 50, 44, 1],
       [1, 0.0, 0.0, 1.0, 58, 39, 1],
       [1, 0.0, 0.0, 1.0, 59, 41, 1],
       [1, 0.0, 0.0, 1.0, 62, 55, 1],
       [1, 1.0, 0.0, 0.0, 70, 47, 0],
       [1, 1.0, 0.0, 0.0, 90, 23, 0],
       [1, 1.0, 0.0, 0.0, 80, 27, 0],
       [1, 1.0, 0.0, 0.0, 88, 28, 0],
       [1, 1.0, 0.0, 0.0, 40, 29, 1],
       [1, 1.0, 0.0, 0.0, 66, 32, 1],
       [1, 1.0, 0.0, 0.0, 56, 42, 1]], dtype=object)